// Redux action types
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_ORDERS_FOR_CUSTOMER = 'SET_ORDERS_FOR_CUSTOMER';
export const DATE_RANGE_SELECTION = 'DATE_RANGE_SELECTION';
export const CUSTOMER_SELECTION = 'CUSTOMER_SELECTION';
